trigger:
  branches:
    include:
      - main
      - feature/*
pool:
  name: Default
jobs:
  - job: build_docker
    displayName: Build Docker Image
    steps:
      - script: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        displayName: Set up QEMU
      - script: |-
          docker buildx create --use --name mybuilder --driver docker-container --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          docker buildx inspect --bootstrap
        displayName: Set up Docker Buildx
      - task: Docker@2
        displayName: Build docker image
        inputs:
          command: build
          Dockerfile: '**/Dockerfile'
          tags: latest
          buildArguments: '--build-arg MARTINI_VERSION=latest'
      # Here add commands to push your docker image to your registry, e.g. using Docker@2 task or a script step with 'docker push' command
