trigger:
  branches:
    include:
      - main
      - feature/*
pool:
  name: Default
jobs:
  - job: deploy_martini_packages
    displayName: Deploy Martini Packages
    steps:
      - task: martiniUploadPackageTask@2
        inputs:
          PACKAGE_NAME_PATTERN: ^(new-package)$
        env:
          BASE_URL: https://localhost:8080
          MARTINI_ACCESS_TOKEN: $(MARTINI_ACCESS_TOKEN)
